-- 코드를 입력하세요
SELECT usr.USER_ID, usr.NICKNAME, SUM(PRICE) as PRICE_SUM
FROM USED_GOODS_BOARD board
INNER JOIN USED_GOODS_USER usr
ON board.WRITER_ID = usr.USER_ID
WHERE board.STATUS = 'DONE'
GROUP BY usr.USER_ID, usr.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE) ASC;