-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * bs.SALES)TOTAL_SALES
FROM BOOK b, AUTHOR a, 
    (SELECT BOOK_ID, SALES, SALES_DATE FROM BOOK_SALES) bs
WHERE b.AUTHOR_ID = a.AUTHOR_ID
AND b.BOOK_ID = bs.BOOK_ID
AND TO_CHAR(bs.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY CATEGORY, a.AUTHOR_ID, a.AUTHOR_NAME
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC;