-- 코드를 입력하세요
SELECT DISTINCT crcrh.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR crcc
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
ON crcc.CAR_ID = crcrh.CAR_ID
WHERE 1 = 1
AND SUBSTR(crcrh.START_DATE, 6, 2) = '10'
AND crcc.CAR_TYPE = '세단'
ORDER BY crcrh.CAR_ID DESC;