-- 코드를 입력하세요
-- SELECT ai.ANIMAL_ID, ai.NAME FROM ANIMAL_INS ai, ANIMAL_OUTS ao
-- WHERE ai.ANIMAL_ID = ao.ANIMAL_ID
-- AND ai.DATETIME > ao.DATETIME
-- ORDER BY ai.DATETIME;

SELECT ai.ANIMAL_ID, ai.NAME
FROM ANIMAL_INS ai, ANIMAL_OUTS ao
WHERE ai.ANIMAL_ID = ao.ANIMAL_ID
AND ai.DATETIME > ao.DATETIME
ORDER BY ai.DATETIME;